#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPA.BD
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ProyectoBD")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertBuses(Buses instance);
    partial void UpdateBuses(Buses instance);
    partial void DeleteBuses(Buses instance);
    partial void InsertSesion(Sesion instance);
    partial void UpdateSesion(Sesion instance);
    partial void DeleteSesion(Sesion instance);
    partial void InsertCarrera(Carrera instance);
    partial void UpdateCarrera(Carrera instance);
    partial void DeleteCarrera(Carrera instance);
    partial void InsertChofer(Chofer instance);
    partial void UpdateChofer(Chofer instance);
    partial void DeleteChofer(Chofer instance);
    partial void InsertRuta(Ruta instance);
    partial void UpdateRuta(Ruta instance);
    partial void DeleteRuta(Ruta instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::ProyectoPA.Properties.Settings.Default.ProyectoBDConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Buses> Buses
		{
			get
			{
				return this.GetTable<Buses>();
			}
		}
		
		public System.Data.Linq.Table<Sesion> Sesion
		{
			get
			{
				return this.GetTable<Sesion>();
			}
		}
		
		public System.Data.Linq.Table<Carrera> Carrera
		{
			get
			{
				return this.GetTable<Carrera>();
			}
		}
		
		public System.Data.Linq.Table<Chofer> Chofer
		{
			get
			{
				return this.GetTable<Chofer>();
			}
		}
		
		public System.Data.Linq.Table<Ruta> Ruta
		{
			get
			{
				return this.GetTable<Ruta>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ActualizarBuses")]
		public int ActualizarBuses([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdBus", DbType="Int")] System.Nullable<int> idBus, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Placa", DbType="VarChar(10)")] string placa, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Modelo", DbType="VarChar(50)")] string modelo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Dueno", DbType="VarChar(50)")] string dueno, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NoBus", DbType="Int")] System.Nullable<int> noBus)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idBus, placa, modelo, dueno, noBus);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ListarSesion")]
		public ISingleResult<ListarSesionResult> ListarSesion()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ListarSesionResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ActualizarCarrera")]
		public int ActualizarCarrera([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCarrera", DbType="Int")] System.Nullable<int> idCarrera, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdBus", DbType="Int")] System.Nullable<int> idBus, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdRuta", DbType="Int")] System.Nullable<int> idRuta, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdChofer", DbType="Int")] System.Nullable<int> idChofer, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HoraSalida", DbType="DateTime")] System.Nullable<System.DateTime> horaSalida, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HoraLlegada", DbType="DateTime")] System.Nullable<System.DateTime> horaLlegada, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estado", DbType="VarChar(10)")] string estado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCarrera, idBus, idRuta, idChofer, horaSalida, horaLlegada, estado);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ActualizarChofer")]
		public int ActualizarChofer([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdChofer", DbType="Int")] System.Nullable<int> idChofer, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombres", DbType="VarChar(10)")] string nombres, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Apellidos", DbType="VarChar(10)")] string apellidos, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TipoLicencia", DbType="VarChar(10)")] string tipoLicencia, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cedula", DbType="VarChar(10)")] string cedula)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idChofer, nombres, apellidos, tipoLicencia, cedula);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ActualizarRuta")]
		public int ActualizarRuta([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdRuta", DbType="Int")] System.Nullable<int> idRuta, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreRuta", DbType="VarChar(50)")] string nombreRuta, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tarifa", DbType="Money")] System.Nullable<decimal> tarifa)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idRuta, nombreRuta, tarifa);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ActualizarSesion")]
		public int ActualizarSesion([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdSesion", DbType="Int")] System.Nullable<int> idSesion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Usuario", DbType="VarChar(10)")] string usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Contrasena", DbType="VarChar(10)")] string contrasena, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tipo", DbType="VarChar(10)")] string tipo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idSesion, usuario, contrasena, tipo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.EliminarBuses")]
		public int EliminarBuses([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdBus", DbType="Int")] System.Nullable<int> idBus, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Placa", DbType="VarChar(10)")] string placa, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Modelo", DbType="VarChar(50)")] string modelo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Dueno", DbType="VarChar(50)")] string dueno, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NoBus", DbType="Int")] System.Nullable<int> noBus)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idBus, placa, modelo, dueno, noBus);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.EliminarChofer")]
		public int EliminarChofer([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdChofer", DbType="Int")] System.Nullable<int> idChofer, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombres", DbType="VarChar(10)")] string nombres, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Apellidos", DbType="VarChar(10)")] string apellidos, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TipoLicencia", DbType="VarChar(10)")] string tipoLicencia, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cedula", DbType="VarChar(10)")] string cedula)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idChofer, nombres, apellidos, tipoLicencia, cedula);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.EliminarRuta")]
		public int EliminarRuta([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdRuta", DbType="Int")] System.Nullable<int> idRuta, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreRuta", DbType="VarChar(50)")] string nombreRuta, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tarifa", DbType="Money")] System.Nullable<decimal> tarifa)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idRuta, nombreRuta, tarifa);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.EliminarSesion")]
		public int EliminarSesion([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdSesion", DbType="Int")] System.Nullable<int> idSesion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Usuario", DbType="VarChar(10)")] string usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Contrasena", DbType="VarChar(10)")] string contrasena, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tipo", DbType="VarChar(10)")] string tipo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idSesion, usuario, contrasena, tipo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertarBuses")]
		public int InsertarBuses([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdBus", DbType="Int")] System.Nullable<int> idBus, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Placa", DbType="VarChar(10)")] string placa, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Modelo", DbType="VarChar(50)")] string modelo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Dueno", DbType="VarChar(50)")] string dueno, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NoBus", DbType="Int")] System.Nullable<int> noBus)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idBus, placa, modelo, dueno, noBus);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertarCarrera")]
		public int InsertarCarrera([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCarrera", DbType="Int")] System.Nullable<int> idCarrera, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdBus", DbType="Int")] System.Nullable<int> idBus, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdRuta", DbType="Int")] System.Nullable<int> idRuta, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdChofer", DbType="Int")] System.Nullable<int> idChofer, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HoraSalida", DbType="DateTime")] System.Nullable<System.DateTime> horaSalida, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HoraLlegada", DbType="DateTime")] System.Nullable<System.DateTime> horaLlegada, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estado", DbType="VarChar(10)")] string estado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCarrera, idBus, idRuta, idChofer, horaSalida, horaLlegada, estado);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertarChofer")]
		public int InsertarChofer([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdChofer", DbType="Int")] System.Nullable<int> idChofer, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombres", DbType="VarChar(10)")] string nombres, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Apellidos", DbType="VarChar(10)")] string apellidos, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TipoLicencia", DbType="VarChar(10)")] string tipoLicencia, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cedula", DbType="VarChar(10)")] string cedula)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idChofer, nombres, apellidos, tipoLicencia, cedula);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertarRuta")]
		public int InsertarRuta([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdRuta", DbType="Int")] System.Nullable<int> idRuta, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreRuta", DbType="VarChar(50)")] string nombreRuta, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tarifa", DbType="Money")] System.Nullable<decimal> tarifa)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idRuta, nombreRuta, tarifa);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertarSesion")]
		public int InsertarSesion([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdSesion", DbType="Int")] System.Nullable<int> idSesion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Usuario", DbType="VarChar(10)")] string usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Contrasena", DbType="VarChar(10)")] string contrasena, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tipo", DbType="VarChar(10)")] string tipo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idSesion, usuario, contrasena, tipo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ListarBuses")]
		public ISingleResult<ListarBusesResult> ListarBuses()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ListarBusesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ListarBusFiltrar")]
		public ISingleResult<ListarBusFiltrarResult> ListarBusFiltrar([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string valor)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), valor);
			return ((ISingleResult<ListarBusFiltrarResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ListarCarrera")]
		public ISingleResult<ListarCarreraResult> ListarCarrera()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ListarCarreraResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ListarCarreraFiltrar")]
		public ISingleResult<ListarCarreraFiltrarResult> ListarCarreraFiltrar([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string valor)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), valor);
			return ((ISingleResult<ListarCarreraFiltrarResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ListarChofer")]
		public ISingleResult<ListarChoferResult> ListarChofer()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ListarChoferResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ListarChoferFiltrar")]
		public ISingleResult<ListarChoferFiltrarResult> ListarChoferFiltrar([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string valor)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), valor);
			return ((ISingleResult<ListarChoferFiltrarResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ListarRuta")]
		public ISingleResult<ListarRutaResult> ListarRuta()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ListarRutaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ListarRutaFiltrar")]
		public ISingleResult<ListarRutaFiltrarResult> ListarRutaFiltrar([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string valor)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), valor);
			return ((ISingleResult<ListarRutaFiltrarResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Buses")]
	public partial class Buses : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDBus;
		
		private string _Placa;
		
		private string _Modelo;
		
		private string _Dueno;
		
		private int _NoBus;
		
		private EntitySet<Carrera> _Carrera;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDBusChanging(int value);
    partial void OnIDBusChanged();
    partial void OnPlacaChanging(string value);
    partial void OnPlacaChanged();
    partial void OnModeloChanging(string value);
    partial void OnModeloChanged();
    partial void OnDuenoChanging(string value);
    partial void OnDuenoChanged();
    partial void OnNoBusChanging(int value);
    partial void OnNoBusChanged();
    #endregion
		
		public Buses()
		{
			this._Carrera = new EntitySet<Carrera>(new Action<Carrera>(this.attach_Carrera), new Action<Carrera>(this.detach_Carrera));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDBus", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDBus
		{
			get
			{
				return this._IDBus;
			}
			set
			{
				if ((this._IDBus != value))
				{
					this.OnIDBusChanging(value);
					this.SendPropertyChanging();
					this._IDBus = value;
					this.SendPropertyChanged("IDBus");
					this.OnIDBusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Placa", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Placa
		{
			get
			{
				return this._Placa;
			}
			set
			{
				if ((this._Placa != value))
				{
					this.OnPlacaChanging(value);
					this.SendPropertyChanging();
					this._Placa = value;
					this.SendPropertyChanged("Placa");
					this.OnPlacaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Modelo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Modelo
		{
			get
			{
				return this._Modelo;
			}
			set
			{
				if ((this._Modelo != value))
				{
					this.OnModeloChanging(value);
					this.SendPropertyChanging();
					this._Modelo = value;
					this.SendPropertyChanged("Modelo");
					this.OnModeloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dueno", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Dueno
		{
			get
			{
				return this._Dueno;
			}
			set
			{
				if ((this._Dueno != value))
				{
					this.OnDuenoChanging(value);
					this.SendPropertyChanging();
					this._Dueno = value;
					this.SendPropertyChanged("Dueno");
					this.OnDuenoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoBus", DbType="Int NOT NULL")]
		public int NoBus
		{
			get
			{
				return this._NoBus;
			}
			set
			{
				if ((this._NoBus != value))
				{
					this.OnNoBusChanging(value);
					this.SendPropertyChanging();
					this._NoBus = value;
					this.SendPropertyChanged("NoBus");
					this.OnNoBusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Buses_Carrera", Storage="_Carrera", ThisKey="IDBus", OtherKey="IDBus")]
		public EntitySet<Carrera> Carrera
		{
			get
			{
				return this._Carrera;
			}
			set
			{
				this._Carrera.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Carrera(Carrera entity)
		{
			this.SendPropertyChanging();
			entity.Buses = this;
		}
		
		private void detach_Carrera(Carrera entity)
		{
			this.SendPropertyChanging();
			entity.Buses = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sesion")]
	public partial class Sesion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDSesion;
		
		private string _Usuario;
		
		private string _Contrasena;
		
		private string _Tipo;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDSesionChanging(int value);
    partial void OnIDSesionChanged();
    partial void OnUsuarioChanging(string value);
    partial void OnUsuarioChanged();
    partial void OnContrasenaChanging(string value);
    partial void OnContrasenaChanged();
    partial void OnTipoChanging(string value);
    partial void OnTipoChanged();
    #endregion
		
		public Sesion()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDSesion", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDSesion
		{
			get
			{
				return this._IDSesion;
			}
			set
			{
				if ((this._IDSesion != value))
				{
					this.OnIDSesionChanging(value);
					this.SendPropertyChanging();
					this._IDSesion = value;
					this.SendPropertyChanged("IDSesion");
					this.OnIDSesionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this.OnUsuarioChanging(value);
					this.SendPropertyChanging();
					this._Usuario = value;
					this.SendPropertyChanged("Usuario");
					this.OnUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contrasena", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Contrasena
		{
			get
			{
				return this._Contrasena;
			}
			set
			{
				if ((this._Contrasena != value))
				{
					this.OnContrasenaChanging(value);
					this.SendPropertyChanging();
					this._Contrasena = value;
					this.SendPropertyChanged("Contrasena");
					this.OnContrasenaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Tipo
		{
			get
			{
				return this._Tipo;
			}
			set
			{
				if ((this._Tipo != value))
				{
					this.OnTipoChanging(value);
					this.SendPropertyChanging();
					this._Tipo = value;
					this.SendPropertyChanged("Tipo");
					this.OnTipoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Carrera")]
	public partial class Carrera : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDCarrera;
		
		private System.DateTime _Tiempo;
		
		private System.DateTime _HoraLlegada;
		
		private string _Estado;
		
		private System.Nullable<int> _IDBus;
		
		private System.Nullable<int> _IDRuta;
		
		private System.Nullable<int> _IDChofer;
		
		private EntityRef<Buses> _Buses;
		
		private EntityRef<Chofer> _Chofer;
		
		private EntityRef<Ruta> _Ruta;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDCarreraChanging(int value);
    partial void OnIDCarreraChanged();
    partial void OnTiempoChanging(System.DateTime value);
    partial void OnTiempoChanged();
    partial void OnHoraLlegadaChanging(System.DateTime value);
    partial void OnHoraLlegadaChanged();
    partial void OnEstadoChanging(string value);
    partial void OnEstadoChanged();
    partial void OnIDBusChanging(System.Nullable<int> value);
    partial void OnIDBusChanged();
    partial void OnIDRutaChanging(System.Nullable<int> value);
    partial void OnIDRutaChanged();
    partial void OnIDChoferChanging(System.Nullable<int> value);
    partial void OnIDChoferChanged();
    #endregion
		
		public Carrera()
		{
			this._Buses = default(EntityRef<Buses>);
			this._Chofer = default(EntityRef<Chofer>);
			this._Ruta = default(EntityRef<Ruta>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCarrera", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDCarrera
		{
			get
			{
				return this._IDCarrera;
			}
			set
			{
				if ((this._IDCarrera != value))
				{
					this.OnIDCarreraChanging(value);
					this.SendPropertyChanging();
					this._IDCarrera = value;
					this.SendPropertyChanged("IDCarrera");
					this.OnIDCarreraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tiempo", DbType="DateTime NOT NULL")]
		public System.DateTime Tiempo
		{
			get
			{
				return this._Tiempo;
			}
			set
			{
				if ((this._Tiempo != value))
				{
					this.OnTiempoChanging(value);
					this.SendPropertyChanging();
					this._Tiempo = value;
					this.SendPropertyChanged("Tiempo");
					this.OnTiempoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoraLlegada", DbType="DateTime NOT NULL")]
		public System.DateTime HoraLlegada
		{
			get
			{
				return this._HoraLlegada;
			}
			set
			{
				if ((this._HoraLlegada != value))
				{
					this.OnHoraLlegadaChanging(value);
					this.SendPropertyChanging();
					this._HoraLlegada = value;
					this.SendPropertyChanged("HoraLlegada");
					this.OnHoraLlegadaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDBus", DbType="Int")]
		public System.Nullable<int> IDBus
		{
			get
			{
				return this._IDBus;
			}
			set
			{
				if ((this._IDBus != value))
				{
					if (this._Buses.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDBusChanging(value);
					this.SendPropertyChanging();
					this._IDBus = value;
					this.SendPropertyChanged("IDBus");
					this.OnIDBusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDRuta", DbType="Int")]
		public System.Nullable<int> IDRuta
		{
			get
			{
				return this._IDRuta;
			}
			set
			{
				if ((this._IDRuta != value))
				{
					if (this._Ruta.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDRutaChanging(value);
					this.SendPropertyChanging();
					this._IDRuta = value;
					this.SendPropertyChanged("IDRuta");
					this.OnIDRutaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDChofer", DbType="Int")]
		public System.Nullable<int> IDChofer
		{
			get
			{
				return this._IDChofer;
			}
			set
			{
				if ((this._IDChofer != value))
				{
					if (this._Chofer.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDChoferChanging(value);
					this.SendPropertyChanging();
					this._IDChofer = value;
					this.SendPropertyChanged("IDChofer");
					this.OnIDChoferChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Buses_Carrera", Storage="_Buses", ThisKey="IDBus", OtherKey="IDBus", IsForeignKey=true)]
		public Buses Buses
		{
			get
			{
				return this._Buses.Entity;
			}
			set
			{
				Buses previousValue = this._Buses.Entity;
				if (((previousValue != value) 
							|| (this._Buses.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Buses.Entity = null;
						previousValue.Carrera.Remove(this);
					}
					this._Buses.Entity = value;
					if ((value != null))
					{
						value.Carrera.Add(this);
						this._IDBus = value.IDBus;
					}
					else
					{
						this._IDBus = default(Nullable<int>);
					}
					this.SendPropertyChanged("Buses");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Chofer_Carrera", Storage="_Chofer", ThisKey="IDChofer", OtherKey="IDChofer", IsForeignKey=true)]
		public Chofer Chofer
		{
			get
			{
				return this._Chofer.Entity;
			}
			set
			{
				Chofer previousValue = this._Chofer.Entity;
				if (((previousValue != value) 
							|| (this._Chofer.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Chofer.Entity = null;
						previousValue.Carrera.Remove(this);
					}
					this._Chofer.Entity = value;
					if ((value != null))
					{
						value.Carrera.Add(this);
						this._IDChofer = value.IDChofer;
					}
					else
					{
						this._IDChofer = default(Nullable<int>);
					}
					this.SendPropertyChanged("Chofer");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ruta_Carrera", Storage="_Ruta", ThisKey="IDRuta", OtherKey="IDRuta", IsForeignKey=true)]
		public Ruta Ruta
		{
			get
			{
				return this._Ruta.Entity;
			}
			set
			{
				Ruta previousValue = this._Ruta.Entity;
				if (((previousValue != value) 
							|| (this._Ruta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Ruta.Entity = null;
						previousValue.Carrera.Remove(this);
					}
					this._Ruta.Entity = value;
					if ((value != null))
					{
						value.Carrera.Add(this);
						this._IDRuta = value.IDRuta;
					}
					else
					{
						this._IDRuta = default(Nullable<int>);
					}
					this.SendPropertyChanged("Ruta");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Chofer")]
	public partial class Chofer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDChofer;
		
		private string _Nombres;
		
		private string _Apellidos;
		
		private string _TipoLicencia;
		
		private string _Cedula;
		
		private EntitySet<Carrera> _Carrera;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChoferChanging(int value);
    partial void OnIDChoferChanged();
    partial void OnNombresChanging(string value);
    partial void OnNombresChanged();
    partial void OnApellidosChanging(string value);
    partial void OnApellidosChanged();
    partial void OnTipoLicenciaChanging(string value);
    partial void OnTipoLicenciaChanged();
    partial void OnCedulaChanging(string value);
    partial void OnCedulaChanged();
    #endregion
		
		public Chofer()
		{
			this._Carrera = new EntitySet<Carrera>(new Action<Carrera>(this.attach_Carrera), new Action<Carrera>(this.detach_Carrera));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDChofer", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDChofer
		{
			get
			{
				return this._IDChofer;
			}
			set
			{
				if ((this._IDChofer != value))
				{
					this.OnIDChoferChanging(value);
					this.SendPropertyChanging();
					this._IDChofer = value;
					this.SendPropertyChanged("IDChofer");
					this.OnIDChoferChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombres", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Nombres
		{
			get
			{
				return this._Nombres;
			}
			set
			{
				if ((this._Nombres != value))
				{
					this.OnNombresChanging(value);
					this.SendPropertyChanging();
					this._Nombres = value;
					this.SendPropertyChanged("Nombres");
					this.OnNombresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellidos", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Apellidos
		{
			get
			{
				return this._Apellidos;
			}
			set
			{
				if ((this._Apellidos != value))
				{
					this.OnApellidosChanging(value);
					this.SendPropertyChanging();
					this._Apellidos = value;
					this.SendPropertyChanged("Apellidos");
					this.OnApellidosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoLicencia", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string TipoLicencia
		{
			get
			{
				return this._TipoLicencia;
			}
			set
			{
				if ((this._TipoLicencia != value))
				{
					this.OnTipoLicenciaChanging(value);
					this.SendPropertyChanging();
					this._TipoLicencia = value;
					this.SendPropertyChanged("TipoLicencia");
					this.OnTipoLicenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cedula", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Cedula
		{
			get
			{
				return this._Cedula;
			}
			set
			{
				if ((this._Cedula != value))
				{
					this.OnCedulaChanging(value);
					this.SendPropertyChanging();
					this._Cedula = value;
					this.SendPropertyChanged("Cedula");
					this.OnCedulaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Chofer_Carrera", Storage="_Carrera", ThisKey="IDChofer", OtherKey="IDChofer")]
		public EntitySet<Carrera> Carrera
		{
			get
			{
				return this._Carrera;
			}
			set
			{
				this._Carrera.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Carrera(Carrera entity)
		{
			this.SendPropertyChanging();
			entity.Chofer = this;
		}
		
		private void detach_Carrera(Carrera entity)
		{
			this.SendPropertyChanging();
			entity.Chofer = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ruta")]
	public partial class Ruta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDRuta;
		
		private string _NombreRuta;
		
		private decimal _Tarifa;
		
		private EntitySet<Carrera> _Carrera;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDRutaChanging(int value);
    partial void OnIDRutaChanged();
    partial void OnNombreRutaChanging(string value);
    partial void OnNombreRutaChanged();
    partial void OnTarifaChanging(decimal value);
    partial void OnTarifaChanged();
    #endregion
		
		public Ruta()
		{
			this._Carrera = new EntitySet<Carrera>(new Action<Carrera>(this.attach_Carrera), new Action<Carrera>(this.detach_Carrera));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDRuta", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDRuta
		{
			get
			{
				return this._IDRuta;
			}
			set
			{
				if ((this._IDRuta != value))
				{
					this.OnIDRutaChanging(value);
					this.SendPropertyChanging();
					this._IDRuta = value;
					this.SendPropertyChanged("IDRuta");
					this.OnIDRutaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreRuta", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NombreRuta
		{
			get
			{
				return this._NombreRuta;
			}
			set
			{
				if ((this._NombreRuta != value))
				{
					this.OnNombreRutaChanging(value);
					this.SendPropertyChanging();
					this._NombreRuta = value;
					this.SendPropertyChanged("NombreRuta");
					this.OnNombreRutaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tarifa", DbType="Money NOT NULL")]
		public decimal Tarifa
		{
			get
			{
				return this._Tarifa;
			}
			set
			{
				if ((this._Tarifa != value))
				{
					this.OnTarifaChanging(value);
					this.SendPropertyChanging();
					this._Tarifa = value;
					this.SendPropertyChanged("Tarifa");
					this.OnTarifaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ruta_Carrera", Storage="_Carrera", ThisKey="IDRuta", OtherKey="IDRuta")]
		public EntitySet<Carrera> Carrera
		{
			get
			{
				return this._Carrera;
			}
			set
			{
				this._Carrera.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Carrera(Carrera entity)
		{
			this.SendPropertyChanging();
			entity.Ruta = this;
		}
		
		private void detach_Carrera(Carrera entity)
		{
			this.SendPropertyChanging();
			entity.Ruta = null;
		}
	}
	
	public partial class ListarSesionResult
	{
		
		private int _IDSesion;
		
		private string _Usuario;
		
		private string _Contrasena;
		
		private string _Tipo;
		
		public ListarSesionResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDSesion", DbType="Int NOT NULL")]
		public int IDSesion
		{
			get
			{
				return this._IDSesion;
			}
			set
			{
				if ((this._IDSesion != value))
				{
					this._IDSesion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this._Usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contrasena", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Contrasena
		{
			get
			{
				return this._Contrasena;
			}
			set
			{
				if ((this._Contrasena != value))
				{
					this._Contrasena = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Tipo
		{
			get
			{
				return this._Tipo;
			}
			set
			{
				if ((this._Tipo != value))
				{
					this._Tipo = value;
				}
			}
		}
	}
	
	public partial class ListarBusesResult
	{
		
		private int _IDBus;
		
		private string _Placa;
		
		private string _Modelo;
		
		private string _Dueno;
		
		private int _NoBus;
		
		public ListarBusesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDBus", DbType="Int NOT NULL")]
		public int IDBus
		{
			get
			{
				return this._IDBus;
			}
			set
			{
				if ((this._IDBus != value))
				{
					this._IDBus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Placa", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Placa
		{
			get
			{
				return this._Placa;
			}
			set
			{
				if ((this._Placa != value))
				{
					this._Placa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Modelo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Modelo
		{
			get
			{
				return this._Modelo;
			}
			set
			{
				if ((this._Modelo != value))
				{
					this._Modelo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dueno", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Dueno
		{
			get
			{
				return this._Dueno;
			}
			set
			{
				if ((this._Dueno != value))
				{
					this._Dueno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoBus", DbType="Int NOT NULL")]
		public int NoBus
		{
			get
			{
				return this._NoBus;
			}
			set
			{
				if ((this._NoBus != value))
				{
					this._NoBus = value;
				}
			}
		}
	}
	
	public partial class ListarBusFiltrarResult
	{
		
		private int _IDBus;
		
		private string _Placa;
		
		private string _Modelo;
		
		private string _Dueno;
		
		private int _NoBus;
		
		public ListarBusFiltrarResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDBus", DbType="Int NOT NULL")]
		public int IDBus
		{
			get
			{
				return this._IDBus;
			}
			set
			{
				if ((this._IDBus != value))
				{
					this._IDBus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Placa", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Placa
		{
			get
			{
				return this._Placa;
			}
			set
			{
				if ((this._Placa != value))
				{
					this._Placa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Modelo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Modelo
		{
			get
			{
				return this._Modelo;
			}
			set
			{
				if ((this._Modelo != value))
				{
					this._Modelo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dueno", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Dueno
		{
			get
			{
				return this._Dueno;
			}
			set
			{
				if ((this._Dueno != value))
				{
					this._Dueno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoBus", DbType="Int NOT NULL")]
		public int NoBus
		{
			get
			{
				return this._NoBus;
			}
			set
			{
				if ((this._NoBus != value))
				{
					this._NoBus = value;
				}
			}
		}
	}
	
	public partial class ListarCarreraResult
	{
		
		private int _IDCarrera;
		
		private System.DateTime _Tiempo;
		
		private System.DateTime _HoraLlegada;
		
		private string _Estado;
		
		private System.Nullable<int> _IDBus;
		
		private System.Nullable<int> _IDRuta;
		
		private System.Nullable<int> _IDChofer;
		
		public ListarCarreraResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCarrera", DbType="Int NOT NULL")]
		public int IDCarrera
		{
			get
			{
				return this._IDCarrera;
			}
			set
			{
				if ((this._IDCarrera != value))
				{
					this._IDCarrera = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tiempo", DbType="DateTime NOT NULL")]
		public System.DateTime Tiempo
		{
			get
			{
				return this._Tiempo;
			}
			set
			{
				if ((this._Tiempo != value))
				{
					this._Tiempo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoraLlegada", DbType="DateTime NOT NULL")]
		public System.DateTime HoraLlegada
		{
			get
			{
				return this._HoraLlegada;
			}
			set
			{
				if ((this._HoraLlegada != value))
				{
					this._HoraLlegada = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDBus", DbType="Int")]
		public System.Nullable<int> IDBus
		{
			get
			{
				return this._IDBus;
			}
			set
			{
				if ((this._IDBus != value))
				{
					this._IDBus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDRuta", DbType="Int")]
		public System.Nullable<int> IDRuta
		{
			get
			{
				return this._IDRuta;
			}
			set
			{
				if ((this._IDRuta != value))
				{
					this._IDRuta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDChofer", DbType="Int")]
		public System.Nullable<int> IDChofer
		{
			get
			{
				return this._IDChofer;
			}
			set
			{
				if ((this._IDChofer != value))
				{
					this._IDChofer = value;
				}
			}
		}
	}
	
	public partial class ListarCarreraFiltrarResult
	{
		
		private int _IDCarrera;
		
		private System.DateTime _Tiempo;
		
		private System.DateTime _HoraLlegada;
		
		private string _Estado;
		
		private System.Nullable<int> _IDBus;
		
		private System.Nullable<int> _IDRuta;
		
		private System.Nullable<int> _IDChofer;
		
		public ListarCarreraFiltrarResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCarrera", DbType="Int NOT NULL")]
		public int IDCarrera
		{
			get
			{
				return this._IDCarrera;
			}
			set
			{
				if ((this._IDCarrera != value))
				{
					this._IDCarrera = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tiempo", DbType="DateTime NOT NULL")]
		public System.DateTime Tiempo
		{
			get
			{
				return this._Tiempo;
			}
			set
			{
				if ((this._Tiempo != value))
				{
					this._Tiempo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoraLlegada", DbType="DateTime NOT NULL")]
		public System.DateTime HoraLlegada
		{
			get
			{
				return this._HoraLlegada;
			}
			set
			{
				if ((this._HoraLlegada != value))
				{
					this._HoraLlegada = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDBus", DbType="Int")]
		public System.Nullable<int> IDBus
		{
			get
			{
				return this._IDBus;
			}
			set
			{
				if ((this._IDBus != value))
				{
					this._IDBus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDRuta", DbType="Int")]
		public System.Nullable<int> IDRuta
		{
			get
			{
				return this._IDRuta;
			}
			set
			{
				if ((this._IDRuta != value))
				{
					this._IDRuta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDChofer", DbType="Int")]
		public System.Nullable<int> IDChofer
		{
			get
			{
				return this._IDChofer;
			}
			set
			{
				if ((this._IDChofer != value))
				{
					this._IDChofer = value;
				}
			}
		}
	}
	
	public partial class ListarChoferResult
	{
		
		private int _IDChofer;
		
		private string _Nombres;
		
		private string _Apellidos;
		
		private string _TipoLicencia;
		
		private string _Cedula;
		
		public ListarChoferResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDChofer", DbType="Int NOT NULL")]
		public int IDChofer
		{
			get
			{
				return this._IDChofer;
			}
			set
			{
				if ((this._IDChofer != value))
				{
					this._IDChofer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombres", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Nombres
		{
			get
			{
				return this._Nombres;
			}
			set
			{
				if ((this._Nombres != value))
				{
					this._Nombres = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellidos", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Apellidos
		{
			get
			{
				return this._Apellidos;
			}
			set
			{
				if ((this._Apellidos != value))
				{
					this._Apellidos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoLicencia", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string TipoLicencia
		{
			get
			{
				return this._TipoLicencia;
			}
			set
			{
				if ((this._TipoLicencia != value))
				{
					this._TipoLicencia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cedula", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Cedula
		{
			get
			{
				return this._Cedula;
			}
			set
			{
				if ((this._Cedula != value))
				{
					this._Cedula = value;
				}
			}
		}
	}
	
	public partial class ListarChoferFiltrarResult
	{
		
		private int _IDChofer;
		
		private string _Nombres;
		
		private string _Apellidos;
		
		private string _TipoLicencia;
		
		private string _Cedula;
		
		public ListarChoferFiltrarResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDChofer", DbType="Int NOT NULL")]
		public int IDChofer
		{
			get
			{
				return this._IDChofer;
			}
			set
			{
				if ((this._IDChofer != value))
				{
					this._IDChofer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombres", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Nombres
		{
			get
			{
				return this._Nombres;
			}
			set
			{
				if ((this._Nombres != value))
				{
					this._Nombres = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellidos", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Apellidos
		{
			get
			{
				return this._Apellidos;
			}
			set
			{
				if ((this._Apellidos != value))
				{
					this._Apellidos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoLicencia", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string TipoLicencia
		{
			get
			{
				return this._TipoLicencia;
			}
			set
			{
				if ((this._TipoLicencia != value))
				{
					this._TipoLicencia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cedula", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Cedula
		{
			get
			{
				return this._Cedula;
			}
			set
			{
				if ((this._Cedula != value))
				{
					this._Cedula = value;
				}
			}
		}
	}
	
	public partial class ListarRutaResult
	{
		
		private int _IDRuta;
		
		private string _NombreRuta;
		
		private decimal _Tarifa;
		
		public ListarRutaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDRuta", DbType="Int NOT NULL")]
		public int IDRuta
		{
			get
			{
				return this._IDRuta;
			}
			set
			{
				if ((this._IDRuta != value))
				{
					this._IDRuta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreRuta", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NombreRuta
		{
			get
			{
				return this._NombreRuta;
			}
			set
			{
				if ((this._NombreRuta != value))
				{
					this._NombreRuta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tarifa", DbType="Money NOT NULL")]
		public decimal Tarifa
		{
			get
			{
				return this._Tarifa;
			}
			set
			{
				if ((this._Tarifa != value))
				{
					this._Tarifa = value;
				}
			}
		}
	}
	
	public partial class ListarRutaFiltrarResult
	{
		
		private int _IDRuta;
		
		private string _NombreRuta;
		
		private decimal _Tarifa;
		
		public ListarRutaFiltrarResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDRuta", DbType="Int NOT NULL")]
		public int IDRuta
		{
			get
			{
				return this._IDRuta;
			}
			set
			{
				if ((this._IDRuta != value))
				{
					this._IDRuta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreRuta", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NombreRuta
		{
			get
			{
				return this._NombreRuta;
			}
			set
			{
				if ((this._NombreRuta != value))
				{
					this._NombreRuta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tarifa", DbType="Money NOT NULL")]
		public decimal Tarifa
		{
			get
			{
				return this._Tarifa;
			}
			set
			{
				if ((this._Tarifa != value))
				{
					this._Tarifa = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
